import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex justify-center items-start overflow-y-auto bg-zinc-950">
        <div className="w-full max-w-[480px] min-h-screen bg-black text-white border-x border-white/10 shadow-[0_0_30px_rgba(0,0,0,0.5)] flex flex-col relative">
          {children}
        </div>
      </body>
    </html>
  );
}
